[package]
authors = ["Marcel Müller <neikos@neikos.email>"]
name = "neikos_moe"
version = "0.1.0"

[dependencies]
bcrypt = "0.1.1"
diesel = "0.7"
dotenv = "0.8.0"
dotenv_macros = "0.9.0"
iron = "0.4"
iron-login = "0.5.0"
lazy_static = "0.2.1"
log = "0.3.6"
logger = "0.0.3"
maud = "0.9"
maud-pulldown-cmark = { path = "../maud-pulldown-cmark" }
maud_macros = "0.9"
mount = "0.2"
params = "0.3"
pulldown-cmark = "0.0.8"
r2d2 = "0.7.0"
r2d2-diesel = "0.7.0"
router = "0.2"
staticfile = "0.3.0"
time = "0.1.35"

[dependencies.diesel_codegen]
default-features = false
features = ["postgres"]
version = "0.7"

[dependencies.log4rs]
features = ["yaml"]
version = "0.4.8"
